### ISSUE TITLE
API App Icons - Needs implementing

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray-archiver#26]
At the moment the API only handles App meta data. included in this meta data should be a url to each app's Google play store icon.

Each app on the google play store features a 300x300 .png image of the app's Icon. An example of an icon image can be seen [here](https://lh6.ggpht.com/mp86vbELnqLi2FzvhiKdPX31_oiTRLNyeK8x4IIrbF5eD1D5RdnVwjQP0hwMNR_JdA=w300).

A Small script can be implemented to scrape the google play site to fetch the app's image. Given that an app's meta data is collected from the same location that the image would come from, if an app has meta data then it has an image. The process of fetching app data should happen alongside the collection of meta data.

On the page for a app, Each icon is found in the following set of img tags.
```
<img class="cover-image" src="//lh6.ggpht.com/mp86vbELnqLi2FzvhiKdPX31_oiTRLNyeK8x4IIrbF5eD1D5RdnVwjQP0hwMNR_JdA=w300" alt="Cover art" aria-hidden="true" itemprop="image">
```

It is worth noting however that there are multiple elements with the css ```"cover-image"``` class.

**Comment by deanott** [comment]
all done serving under root though...
