### ISSUE TITLE
DB.go use 'prepared statements'

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray-archiver#27]
At the moment the statements are constructed by adding strings together, need to swap so that the statement is constructed in the following format
```
db.Query("select $1 from $2.foo1 $2.foo2 like any $3 and $2.bar like any $4", bar1, bar2, bar3, bar4)
```

**Comment by AdamSlack** [comment]
Also we have an issue at the moment, where we're actually injecting SQL ourselves. thus we need to change the way we build the query.

**Comment by deanott** [comment]
@sauyon  fixed
