### ISSUE TITLE
Create master table to increase query speed

### ISSUE THREAD

**Issue by deanott** [sociam/xray-archiver#81]
Based on the join on the fullquery a table setup to combine all these would increase speed. 

Should setup triggers in the separate tables to keep this table up to date.

**Comment by AdamSlack** [comment]
what should be done is that the joins happen after selecting all records matching on a title, that way we're not joining on redundant records only to have to filter them based on titles.

**Comment by deanott** [comment]
materialized view of this would increase speed

**Comment by deanott** [comment]
Indexes can then be created on materialized views

**Comment by deanott** [comment]
indexes and materialized views are now used
