### ISSUE TITLE
Query needs to be 'Or' not 'And'

### ISSUE THREAD

**Issue by AdamSlack** [sociam/xray-archiver#84]

**Comment by deanott** [comment]
The main query is for restricting a query and retrieving the data only under that matching criteria. It does take the developer, titles and etc as separate parameters. Therefore, if you're after a company or app called foo, just pass this as a parameter. If it was or we might never get a single app back and restrict the selection. 

If you're after everything that might be called foo then that is a different query. That query function would handle this type of unconstrained searching, without mutilating the restricted search.

**Comment by AdamSlack** [comment]
Perhaps we should take the function you want to have, rename it 'advanced_query' and then have a flag in the params that default to false. Kinda like `api/apps?advanced=true`. Then we should also implement a function that returns all possible matches. A Union of the tables, not an intersection of them.

The reason to have a query that includes both Developers and titles and everything else is cause you don't know what it is that you wanted exactly so you return the most likely matches. And since we assume that the likelihood of a user wanting an app is proportional to the amount of downloads the app has.

Also the use case we have right now is that the user is going to type into a search-bar, there is no advanced search, meaning when the user types a query out, it should perform a Union on all tables that could match, order them by popularity and return top selection limited by the limit param.

The existing implementation may be of use later, but right now an intersect isn't what's needed.
